add orjson
spesmilo/electrumx pull request #53
Opened 2020-08-17 12:45 UTC by poiuty

2020-08-18 07:59 UTC, smmalis37 commented
Are there any benchmarks comparing orjson to the other options? Should it really be the preferred option in cases where more than 1 are present?

2020-08-18 08:12 UTC, poiuty commented
@smmalis37, https://github.com/ijl/orjson#performance

2020-10-12 02:44 UTC, JustinTArthur commented
I have no issue with us supporting orjson as well, will run some benchmarks against typical Bitcoin block serialization. I've restarted the tests for this PR now that they're working again.

2020-10-12 03:00 UTC, JustinTArthur requested changes

2020-10-12 03:00 UTC, JustinTArthur commented on electrumx/lib/util.py
> +print("using", json.__name__)
Can you remove this print statement for now? It should eventually be a `logger.debug` from one of the modules responsible for environment on startup.

2020-12-03 22:49 UTC, smmalis37 commented
Could the json-related note in https://github.com/spesmilo/electrumx/blob/master/docs/PERFORMANCE-NOTES also get updated?

2026-06-26 18:19 UTC, SomberNight commented
done in https://github.com/spesmilo/electrumx/pull/372

2026-06-26 18:19 UTC, closed without merging